### ISSUE TITLE
tmodjs 开发计划

### ISSUE THREAD

**Issue by aui** [aui/tmodjs#39]
1. [ ] 支持配置`.tmodignore`，排除文件 https://github.com/aui/tmodjs/issues/21
2. [ ] 支持 GBK2312 编码 https://github.com/aui/tmodjs/issues/32
3. [ ] `combo`支持自定义打包合并模板 https://github.com/aui/tmodjs/issues/36
4. [ ] `.cache`文件夹优化 https://github.com/aui/tmodjs/issues/35
5. [ ] 内部技术优化，处理 windows 路径分隔符 https://github.com/aui/tmodjs/issues/10
6. [ ] 支持使用后缀名作为模板路径（需要改动 artTemplate）
7. [ ] 进一步改善压缩率
8. [x] 让运行时文件也遵循`type`的设置

**Comment by yanhaijing** [comment]
很棒的思路
